version: '3'

services:
  backend:
    build:
      context: .
      dockerfile: Backend.Dockerfile

    ports:
      - "8081:8081"

    ## Image folders (save them in volume)
    volumes:
      - appdata:/usr/src/appdata
      # - /uploads:/usr/src/app/uploads
      # - /uploads-compressed:/usr/src/app/uploads-compressed
      # - /appdata/appdata:/usr/src/app/appdata

  frontend:
    build:
      context: ./frontend
      dockerfile: ../Frontend.Dockerfile

    ## TODO: Switch this later - might not have cname for 8080
    ports:
      - "8080:8080"

volumes:
  appdata: