# fly.toml file generated for hugos-photos-backend on 2023-03-12T19:48:38+01:00

app = "hugos-photos-backend"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[build]
  dockerfile = "./Backend.Dockerfile"

[mounts]
  source="image_volume"
  destination="/data"

[env]
  PORT = "8080"

[experimental]
  auto_rollback = true
  cmd = "./hugos-photos"

[[services]]
  http_checks = []
  internal_port = 8082
  processes = ["app"]
  protocol = "tcp"
  script_checks = []
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"
