# fly.toml file generated for hugos-photos on 2023-03-05T17:22:16+01:00

app = "hugos-photos"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[experimental]
# required because we can't infer your binary's name
cmd = "./hugos-photos"
auto_rollback = true

[env]
  PORT = "8080"

[[services]]
  http_checks = []
  internal_port = 8082
  processes = ["app"]
  protocol = "tcp"
  script_checks = []
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"
